// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vpvnbziyywtlnfitxbmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwdm5ieml5eXd0bG5maXR4Ym1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyMzAwNzMsImV4cCI6MjA1NzgwNjA3M30.LM052LyQi8NRK81c0BYTdwQZHneiWbjsmS74aMlV0Vk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});